/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    2: typeof import('./src/components/libro copy 2.vue')['default']
    copy: typeof import('./src/components/libro copy.vue')['default']
    Detailbook: typeof import('./src/components/detailbook.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/components/home.vue')['default']
    Libro: typeof import('./src/components/libro.vue')['default']
    Profilo: typeof import('./src/components/profilo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
